name: BiooBang
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch==2.1.1 
  - torchvision==0.16.1 
  - torchaudio==2.1.1 
  - pytorch-cuda=11.8
  - pip=23.3
  - pip:
    - transformers==4.36.2
    - deepspeed==0.13.2
    - accelerate==0.25.0
    - datasets==2.16.1
    - dask==2023.6.0
    - pandas==2.1.3
    - biopython==1.83
    - tqdm==4.66.1
    - scikit-learn==1.3.2
    - matplotlib==3.8.2
    - numpy==1.26.0 
    - scipy==1.11.4
